[tool.ruff]
line-length = 119

[tool.ruff.lint]
# Never enforce `E501` (line length violations).
ignore = ["E501", "E741", "W605"]
select = ["E", "F", "I", "W"]

# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]
"manim_animations/*" = ["ALL"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["accelerate"]

[tool.ruff.format]
exclude = [
    "manim_animations/*"
]
