FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04
LABEL maintainer="Hugging Face"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y python3 python3-pip
RUN python3 -m pip install --no-cache-dir --upgrade pip

WORKDIR /workspace
COPY . accelerate/

RUN python3 -m pip install --no-cache-dir light-the-torch
RUN python3 -m ltt install --no-cache-dir torch

RUN cd accelerate/ && \
    python3 -m pip install --no-cache-dir .