name: Check for dependency modification

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-for-setup:
    runs-on: ubuntu-latest
    name: Check if setup was changed
    outputs:
      changed: ${{ steps.was_changed.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: "2"
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v22.2
      
      - name: Was setup changed 
        id: was_changed
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ `basename "${file}"` = "setup.py" ]; then
              echo ::set-output name=changed::"1"
            fi
          done

  write-message:
    needs: check-for-setup
    if: (github.event_name == 'pull_request') && (needs.check-for-setup.outputs.changed == '1')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jwalton/gh-find-current-pr@v1
      id: find_pr
      with:
        state: open

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install PyGithub
      run: |
        pip install PyGithub

    - run: |
        python utils/check_setup.py
      if: success() && steps.find_pr.outputs.number
      env: 
        PR_NUMBER: ${{ steps.find_pr.outputs.pr }}
        REPO: ${{ github.event.repository.full_name }}

  build-docker-containers:
    needs: check-for-setup
    if: (github.event_name == 'push') && (needs.check-for-setup.outputs.changed == '1')
    uses: ./.github/workflows/build-docker-images.yml