name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Build PR Documentation"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    # if: >
    #   github.event.workflow_run.event == 'pull_request' &&
    #   github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: mytestartifcat
      - name: Display structure of downloaded files
        run: ls -R
# upload to hf hub