name: Test FP8 Runner

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  set-prev-day:
    runs-on: ubuntu-latest
    steps:
      - name: Set PREV_DAY
        run: |
          PREV_DAY=$(date -d "yesterday" '+%Y-%m-%d')
          echo "PREV_DAY=$PREV_DAY" >> $GITHUB_ENV
  run-fp8-tests:
    needs: set-prev-day
    runs-on:
      group: aws-g6e-12xlarge
    container:
      image: huggingface/accelerate:gpu-fp8-transformerengine-nightly-${{ env.PREV_DAY }}
      options: --gpus all --shm-size "16gb"
    steps:
      - uses: actions/checkout@v3
      - name: Run FP8 tests
        shell: bash
        run: |
          source activate accelerate; python -c "from accelerate import Accelerator; Accelerator(mixed_precision='fp8'); print(accelerator.state)"