name: Test FP8 Runner

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  set-prev-day:
    runs-on: ubuntu-latest
    outputs:
      prev-day: ${{ steps.set-prev-day.outputs.prev-day }}
    steps:
      - name: Set PREV_DAY
        id: set-prev-day
        run: |
          PREV_DAY=$(date -d "yesterday" '+%Y-%m-%d')
          echo "prev-day=$PREV_DAY" >> $GITHUB_OUTPUT
  run-fp8-tests:
    needs: set-prev-day
    runs-on:
      group: aws-g6e-12xlarge
    container:
      image: huggingface/accelerate:gpu-fp8-transformerengine-nightly-${{ needs.set-prev-day.outputs.prev-day }}
      options: --gpus all --shm-size "16gb"
    steps:
      - uses: actions/checkout@v3
      - name: Run FP8 tests
        shell: bash
        run: |
          conda activate; conda activate accelerate; python -c "from accelerate import Accelerator; Accelerator(mixed_precision='fp8'); print(accelerator.state)"