name: Test FP8 Runner

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-fp8-tests:
    runs-on:
      group: aws-g6e-12xlarge
    container:
      image: huggingface/accelerate:gpu-fp8-transformerengine-release-1.6.0
      options: --gpus all --shm-size "16gb"
    steps:
      - uses: actions/checkout@v3
      - name: Run FP8 tests
        run: |
          conda activate accelerate; python -c "from accelerate import Accelerator; Accelerator(mixed_precision='fp8'); print(accelerator.state)"