name: Self-hosted runner with slow tests (scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

env:
  RUN_SLOW: "yes"
  IS_GITHUB_CI: "1"
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}


jobs:
  run_tests:
    name: run_tests_${{ matrix.test_type }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_type: single_gpu
            runner: aws-g6-4xlarge-plus
            image: huggingface/accelerate:gpu-nightly
            cuda_visible_devices: "0"
            targets: test test_examples
          - test_type: single_gpu_deepspeed
            runner: aws-g6-4xlarge-plus
            image: huggingface/accelerate:gpu-deepspeed-nightly
            cuda_visible_devices: "0"
            targets: test_deepspeed
          - test_type: multi_gpu
            runner: aws-g6-12xlarge-plus
            image: huggingface/accelerate:gpu-nightly
            cuda_visible_devices: "0,1"
            targets: test test_examples
          - test_type: multi_gpu_deepspeed
            runner: aws-g6-12xlarge-plus
            image: huggingface/accelerate:gpu-deepspeed-nightly
            cuda_visible_devices: "0,1"
            targets: test_deepspeed
    runs-on:
      group: ${{ matrix.runner }}
    env:
      CUDA_VISIBLE_DEVICES: ${{ matrix.cuda_visible_devices }}
      TEST_TYPE: ${{ matrix.test_type }}
    container:
      image: ${{ matrix.image }}
      options: --gpus all --shm-size "16gb"
    defaults:
      run:
        shell: bash
    steps:
      - name: Update clone & pip install
        run: |
          source activate accelerate
          git clone https://github.com/huggingface/accelerate;
          cd accelerate;
          git checkout ${{ github.sha }};
          pip install -e . --no-deps
          pip install pytest-reportlog tabulate

      - name: Show installed libraries
        run: |
          source activate accelerate;
          pip freeze

      - name: Run test suites
        working-directory: accelerate
        run: |
          source activate accelerate
          status=0
          for target in ${{ matrix.targets }}; do
            make $target || status=1
          done
          exit $status

      - name: Generate Report
        working-directory: accelerate
        if: always()
        run: |
          pip install slack_sdk tabulate
          python utils/log_reports.py >> $GITHUB_STEP_SUMMARY

  run-integration-tests:
    if: always()
    uses: ./.github/workflows/self_hosted_integration_tests.yml
